project:
  name: churn_prediction
  random_seed: 42

data:
  raw_path: data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv
  target_col: Churn
  features:
    id_features:
      - customerID  
    numerical_features:
      - tenure
      - MonthlyCharges
      - TotalCharges
    categorical_features:
      - gender
      - SeniorCitizen
      - Partner
      - Dependents
      - PhoneService
      - MultipleLines
      - InternetService
      - OnlineSecurity
      - OnlineBackup
      - DeviceProtection
      - TechSupport
      - StreamingTV
      - StreamingMovies
      - Contract
      - PaperlessBilling
      - PaymentMethod 
training:
  test_size: 0.2
  val_size: 0.2
  active_models:
    - logistic_regression
    - lightgbm

model:
  logistic_regression:
    params:
      C: 1.0
      max_iter: 1000
  lightgbm:
    params:
      n_estimators: 300
      learning_rate: 0.05
      max_depth: -1
      num_leaves: 31
      subsample: 0.8
      colsample_bytree: 0.8
      class_weight: "balanced"
      random_state: 42
      n_jobs: -1
  
